### PR TITLE
feat: add `deep-equal-json`

### LINKED ISSUE #67: Replacing `deep-equal-json`
https://github.com/A11yance/axobject-query/pull/354

### PR DESCRIPTION
**Pull request by SukkaW**
Closes #67.

https://github.com/A11yance/axobject-query/pull/354

### CODE REVIEW

**Comment by valadaptive** [comment]
I'm not sure dequal is equivalent to deep-equal-json--for instance, I believe dequal traverses `Map`s and `Set`s whereas deep-equal-json uses referential equality

**Comment by SukkaW** [comment]
> I'm not sure dequal is equivalent to deep-equal-json--for instance, I believe dequal traverses `Map`s and `Set`s whereas deep-equal-json uses referential equality

The reason behind the alias is that I don't want to re-implement deep equal over and over again. JS community has enough existing implementations on the npm.

Currently, **the only dependent** of the `deep-equal-json` **is** the axe project. What I am really afraid of is that ljharb spread his *toxic* dependencies even further, which could become a serious issue.

**Comment by SukkaW** [comment]
> I'm not sure dequal is equivalent to deep-equal-json--for instance, I believe dequal traverses `Map`s and `Set`s whereas deep-equal-json uses referential equality

@valadaptive 

It seems that `deep-equal-json` is only for JSON-supported values, so `Map` and `Set` might not be an issue.

On the other hand, should I use `dequal/lite` instead? It seems that `dequal/lite` also doesn't include deep `Map` and `Set` comparisons and thus behaves similarly.

**Comment by valadaptive** [comment]
It seems like `dequal/lite` is part of the `dequal` package already--I think that'd be preferable, yeah

**Comment by mikkurogue** [comment]
> Currently, **the only dependent** of the `deep-equal-json` **is** the axe project. What I am really afraid of is that ljharb spread his _toxic_ dependencies even further, which could become a serious compat issue.

Doing God's work ❤️

**Comment by SukkaW** [comment]
> It seems like `dequal/lite` is part of the `dequal` package already

`dequal` is already lightweight enough, thus not a problem. The behavior match is more important in this context.

**Pull request merged**
