### PR TITLE
feat: add `is-core-module`

### LINKED ISSUE #69: [Feature request] `is-core-module`
Can be easily replaced by importing `isBuiltin` from `node:module`

https://nodejs.org/api/module.html#moduleisbuiltinmodulename

### PR DESCRIPTION
**Pull request by SukkaW**
Fixes #69 

cc @dominikg @SuperchupuDev

### CODE REVIEW

**Comment by wojtekmaj** [comment]
@SukkaW Heads-up:

```
➤ YN0035: │ is-core-module@npm:@nolyfill/is-core-module@latest: Package not found
➤ YN0035: │   Response Code: 404 (Not Found)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: https://registry.yarnpkg.com/@nolyfill%2fis-core-module
```

**Comment by SukkaW** [comment]
Oh, not published yet! I was thinking about releasing a new version after #74 is merged.

**Comment by wojtekmaj** [comment]
I don't think these tasks are coupled, but alright, I'll wait! Thanks!

**Comment by SukkaW** [comment]
`1.0.32` is now released!

**Pull request merged**
